/* config.h.  Generated by configure.  */

//
// (TDS) I'm probably not using this config.h.in thing properly.
// If configure.in has AC_CONFIG_HEADERS([config.h]), then configure
// generates a config.h.in 
//

/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "ChomboVis"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "ChomboVis"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Compiler portability stuff */
#if (__GNUC__ > 3) || ( (__GNUC__ == 3) && (__GNUC_MINOR__ > 3) )
#define TEMPLATE_ANGLE_ANGLE template<>
#else
#define TEMPLATE_ANGLE_ANGLE
#endif
/* #undef TEMPLATE_ANGLE_ANGLE */
