#!/bin/sh -x
#
# By me.  Deletes all autoconf-generated stuff that even
# make distclean misses.
#
rm -f aclocal.m4 \
     configure \
     COPYING \
     INSTALL \
     install-sh \
     missing \
     mkinstalldirs \
     config.guess \
     config.sub \
     ltmain.sh \
     depcomp \
     conftest* \
     aclocal.m4 config.cache config.log config.status libtool

for f in `find . -name Makefile.in`; do
    rm $f
done
for f in `find . -name Makefile`; do
    rm $f
done

rm -rf autom4te.cache
