#ifndef INCLUDED_CMDLINE_BASE_HPP
#define INCLUDED_CMDLINE_BASE_HPP

#include "argmap.hpp"
#include <stdlib.h>  // <cstdlib> and getenv not recognized!?
#include <cstdlib>
#include <map>
#include <string>
 
//----------------------------------------------------------------- 
// 
// class CmdlineBase 
// 
// This is intended as a base class for a class Cmdline that generate_cmdline.py
// generates in each project's src directory.  generate_cmdline.py is called
// from each project's Makefile.
//
// Cmdline variables can come from three places:
// 1. The variable definition file, which is in each project's src directory.
//    This file is used by generate_cmdline.py to generate the local
//    cmdline.{c,h}pp and set default values.
// 2. The cmdline file (typically ~/.<project-name>rc).
// 3. The command line.
// 
// The cmdline file is optional, and even when it's there it need not mention
// all the variables.  Values in the cmdline file override defaults from the
// variable definition file.  Values set on the command line override the
// cmdline file as well as the variable definition file.  But when (and if) the
// project calls CmdlineBase::Recmdlineure(), we look at the cmdline file and
// anything that's changed there takes effect, so run-time changes to the
// cmdline file override everything else.
//
// The ArgMap (m_argmap) member might look redundant.  After all, the subclass
// CmdLine -- generated by Python for each project -- has a complete set of
// getters and setters for all the parameters.  m_argmap is nonetheless not
// redundant: we need it to collect the parameters from the command line (and
// figure out if something on the command line is the name of a parameter at
// all); we need it to collect parameters from the ~/.<project>rc file; and
// we need it to list the full set of options, i.e. respond to  --help.  In such
// a role, it's essential that m_argmap stay in sync with the private data
// members of the subclass CmdLine -- and we ensure that by giving each element
// of m_argmap a pointer to its corresponding data member in CmdLine.
//----------------------------------------------------------------- 
 
class CmdlineBase 
{ 
  public: 
     
    CmdlineBase();
    virtual ~CmdlineBase();

    void Reload();
    void PrintCmdlineParams( std::ostream & ) const;

    static int DebugLevel();
    static void DebugLevel( int value);

    // --------------------------------

  protected:
    std::map<std::string,SetType*> m_argmap;

    void LoadDefaultsFromFile();
    void ParseCommandLine( int argc, char *argv[] );
    void SaveCmdlineFileTimestamp();
    void CheckForCmdlineFile( std::string );

    static Anything s_debug_level;  // 0=Fatal, 1=Error, 2=Warning, 3=Info, 4=Trace.

    // ---- end of cmdlineurable parameters -----

    std::string m_cmdlineFilename;   // Full list of params with initial values.
    bool   m_cmdlineFileExists;
    time_t m_lastTouch; // last time cmdline file was touched.

    std::string ArgName( std::string );
    std::string ArgVal( std::string );

  private:
    enum {k_max_line_length=256};
}; 


//
// CmdlineFactory
//
class Cmdline;
class CmdlineFactory
{
public:
    static void Init(Cmdline const&);
    static Cmdline const& TheCmdline();
private:
    static Cmdline const* m_rep;
};


 
#endif // INCLUDED_CMDLINE_BASE_HPP
