#!/bin/sh -x
#
# By me.  Deletes all autoconf-generated stuff that even
# make distclean misses.
#
rm -f Makefile.in \
     aclocal.m4 \
     configure \
     COPYING \
     INSTALL \
     install-sh \
     missing \
     mkinstalldirs \
     config.guess \
     config.sub \
     ltconfig \
     ltmain.sh \
     depcomp

rm -rf autom4te.cache
rm -f `find . -name Makefile.in`
