#!/bin/sh -x
#
# By me.  Generate autoconf stuff; autoreconf doesn't seem to
# do it.
# To delete use ./zap.
#
aclocal                   # Produces aclocal.m4, so autoconf can understand
                          # AM_* statements found in Makefile.am

libtoolize --force

automake --add-missing --foreign   # Produces Makefile.in, and various symlinks.

autoconf                  # Produces configure.
