#!/bin/sh -x
#
# By me.  Deletes all autoconf-generated stuff that even
# make distclean misses.
#
rm -f Makefile.in \
     aclocal.m4 \
     configure \
     COPYING \
     INSTALL \
     install-sh \
     missing \
     mkinstalldirs \
     stamp-h1 \
     config.h config.log config.status config.guess config.sub \
     ltmain.sh \
     depcomp

rm -f `find . -name Makefile.in`
rm -f `find . -name Makefile`
rm -f `find . -name "*~"`
rm -rf `find . -type d -name .deps`
rm -rf `find . -type d -name .libs`

rm -rf autom4te.cache
